<?php
/**
 * PaymentDisputeOutcomeDetail
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.18.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PaymentDisputeOutcomeDetail Class Doc Comment
 *
 * @category Class
 * @description This type is used by the resolution container that is returned for payment disputes that have been resolved.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentDisputeOutcomeDetail implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PaymentDisputeOutcomeDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'fees' => '\Swagger\Client\Model\SimpleAmount',
'protected_amount' => '\Swagger\Client\Model\SimpleAmount',
'protection_status' => 'string',
'reason_for_closure' => 'string',
'recoup_amount' => '\Swagger\Client\Model\SimpleAmount',
'total_fee_credit' => '\Swagger\Client\Model\SimpleAmount'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'fees' => null,
'protected_amount' => null,
'protection_status' => null,
'reason_for_closure' => null,
'recoup_amount' => null,
'total_fee_credit' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fees' => 'fees',
'protected_amount' => 'protectedAmount',
'protection_status' => 'protectionStatus',
'reason_for_closure' => 'reasonForClosure',
'recoup_amount' => 'recoupAmount',
'total_fee_credit' => 'totalFeeCredit'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fees' => 'setFees',
'protected_amount' => 'setProtectedAmount',
'protection_status' => 'setProtectionStatus',
'reason_for_closure' => 'setReasonForClosure',
'recoup_amount' => 'setRecoupAmount',
'total_fee_credit' => 'setTotalFeeCredit'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fees' => 'getFees',
'protected_amount' => 'getProtectedAmount',
'protection_status' => 'getProtectionStatus',
'reason_for_closure' => 'getReasonForClosure',
'recoup_amount' => 'getRecoupAmount',
'total_fee_credit' => 'getTotalFeeCredit'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['fees'] = isset($data['fees']) ? $data['fees'] : null;
        $this->container['protected_amount'] = isset($data['protected_amount']) ? $data['protected_amount'] : null;
        $this->container['protection_status'] = isset($data['protection_status']) ? $data['protection_status'] : null;
        $this->container['reason_for_closure'] = isset($data['reason_for_closure']) ? $data['reason_for_closure'] : null;
        $this->container['recoup_amount'] = isset($data['recoup_amount']) ? $data['recoup_amount'] : null;
        $this->container['total_fee_credit'] = isset($data['total_fee_credit']) ? $data['total_fee_credit'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fees
     *
     * @return \Swagger\Client\Model\SimpleAmount
     */
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     *
     * @param \Swagger\Client\Model\SimpleAmount $fees fees
     *
     * @return $this
     */
    public function setFees($fees)
    {
        $this->container['fees'] = $fees;

        return $this;
    }

    /**
     * Gets protected_amount
     *
     * @return \Swagger\Client\Model\SimpleAmount
     */
    public function getProtectedAmount()
    {
        return $this->container['protected_amount'];
    }

    /**
     * Sets protected_amount
     *
     * @param \Swagger\Client\Model\SimpleAmount $protected_amount protected_amount
     *
     * @return $this
     */
    public function setProtectedAmount($protected_amount)
    {
        $this->container['protected_amount'] = $protected_amount;

        return $this;
    }

    /**
     * Gets protection_status
     *
     * @return string
     */
    public function getProtectionStatus()
    {
        return $this->container['protection_status'];
    }

    /**
     * Sets protection_status
     *
     * @param string $protection_status This enumeration value indicates if the seller is fully protected, partially protected, or not protected by eBay for the payment dispute. This field is always returned once the payment dispute is resolved. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:ProtectionStatusEnum'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setProtectionStatus($protection_status)
    {
        $this->container['protection_status'] = $protection_status;

        return $this;
    }

    /**
     * Gets reason_for_closure
     *
     * @return string
     */
    public function getReasonForClosure()
    {
        return $this->container['reason_for_closure'];
    }

    /**
     * Sets reason_for_closure
     *
     * @param string $reason_for_closure The enumeration value returned in this field indicates the outcome of the payment dispute for the seller. This field is always returned once the payment dispute is resolved. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/fulfillment/types/api:OutcomeEnum'>eBay API documentation</a>
     *
     * @return $this
     */
    public function setReasonForClosure($reason_for_closure)
    {
        $this->container['reason_for_closure'] = $reason_for_closure;

        return $this;
    }

    /**
     * Gets recoup_amount
     *
     * @return \Swagger\Client\Model\SimpleAmount
     */
    public function getRecoupAmount()
    {
        return $this->container['recoup_amount'];
    }

    /**
     * Sets recoup_amount
     *
     * @param \Swagger\Client\Model\SimpleAmount $recoup_amount recoup_amount
     *
     * @return $this
     */
    public function setRecoupAmount($recoup_amount)
    {
        $this->container['recoup_amount'] = $recoup_amount;

        return $this;
    }

    /**
     * Gets total_fee_credit
     *
     * @return \Swagger\Client\Model\SimpleAmount
     */
    public function getTotalFeeCredit()
    {
        return $this->container['total_fee_credit'];
    }

    /**
     * Sets total_fee_credit
     *
     * @param \Swagger\Client\Model\SimpleAmount $total_fee_credit total_fee_credit
     *
     * @return $this
     */
    public function setTotalFeeCredit($total_fee_credit)
    {
        $this->container['total_fee_credit'] = $total_fee_credit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
