<?php
/**
 * CancelRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.18.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CancelRequestTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains information about a buyer request to cancel an order.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CancelRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CancelRequest"
     */
    public function testCancelRequest()
    {
    }

    /**
     * Test attribute "cancel_completed_date"
     */
    public function testPropertyCancelCompletedDate()
    {
    }

    /**
     * Test attribute "cancel_initiator"
     */
    public function testPropertyCancelInitiator()
    {
    }

    /**
     * Test attribute "cancel_reason"
     */
    public function testPropertyCancelReason()
    {
    }

    /**
     * Test attribute "cancel_requested_date"
     */
    public function testPropertyCancelRequestedDate()
    {
    }

    /**
     * Test attribute "cancel_request_id"
     */
    public function testPropertyCancelRequestId()
    {
    }

    /**
     * Test attribute "cancel_request_state"
     */
    public function testPropertyCancelRequestState()
    {
    }
}
