<?php
/**
 * PaymentDisputeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.18.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * PaymentDisputeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentDisputeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for acceptPaymentDispute
     *
     * Accept Payment Dispute.
     *
     */
    public function testAcceptPaymentDispute()
    {
    }

    /**
     * Test case for addEvidence
     *
     * Add an Evidence File.
     *
     */
    public function testAddEvidence()
    {
    }

    /**
     * Test case for contestPaymentDispute
     *
     * Contest Payment Dispute.
     *
     */
    public function testContestPaymentDispute()
    {
    }

    /**
     * Test case for fetchEvidenceContent
     *
     * Get Payment Dispute Evidence File.
     *
     */
    public function testFetchEvidenceContent()
    {
    }

    /**
     * Test case for getActivities
     *
     * Get Payment Dispute Activity.
     *
     */
    public function testGetActivities()
    {
    }

    /**
     * Test case for getPaymentDispute
     *
     * Get Payment Dispute Details.
     *
     */
    public function testGetPaymentDispute()
    {
    }

    /**
     * Test case for getPaymentDisputeSummaries
     *
     * Search Payment Dispute by Filters.
     *
     */
    public function testGetPaymentDisputeSummaries()
    {
    }

    /**
     * Test case for updateEvidence
     *
     * Update evidence.
     *
     */
    public function testUpdateEvidence()
    {
    }

    /**
     * Test case for uploadEvidenceFile
     *
     * Upload an Evidence File.
     *
     */
    public function testUploadEvidenceFile()
    {
    }
}
